---
- name: remove dns entries for each tower node
  include_tasks: teardown.yml
  when: teardown|bool

- name: check to see if SSL cert already applied
  uri:
    url: "https://{{username}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}/api/v2/ping/"
    method: GET
    user: admin
    password: "{{admin_password}}"
    validate_certs: true
    force_basic_auth: true
  register: check_cert
  ignore_errors: true
  failed_when: false
  when:
    - not teardown

- name: create DNS entries for Ansible Tower and SSL cert
  block:
    - name: create DNS entries for each Ansible Tower node
      include_tasks: create.yml

    - name: certbot for Ansible Tower
      include_tasks: tower.yml

    - name: make sure Ansible Tower is started
      service:
        name: ansible-tower.service
        state: started
      register: install_tower
      until: install_tower is not failed
      retries: 5
  when:
    - not teardown
    - check_cert.status != 200
