---
- name: makesure bigip is online
  hosts: lb
  connection: local
  gather_facts: false


  tasks:
    - name: check bigip to make sure it is online
      uri:
        url: "https://{{ ansible_host }}:8443/mgmt/shared"
        method: GET
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      register: f5networks
      until: f5networks is not failed
      retries: 30
