---
- name: Configure GitLab Host
  hosts: gitlab
  become: true
  gather_facts: true
  tags:
    - gitlab
  tasks:
    - include_role:
        name: common
    - include_role:
        name: gitlab-server
    - include_role:
        name: geerlingguy.gitlab
      vars:
        gitlab_version: '13.6.7-ce.0.el8'
        gitlab_external_url: "https://gitlab.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    - include_role:
        name: gitlab-server
        tasks_from: add-users

- name: Configure GitLab client
  hosts: '*ansible-1'
  become: true
  gather_facts: true
  tags:
    - git
  roles:
    - gitlab-client
